interactive:
  our mission: "Improving the education and opportunities of African-American and lower income families through strategic partnerships with community and faith-based organizations."
  our vision: "By 2013, we envision thriving children, families and communities anchored by a network of accountable, collaborative community, educational and faith organizations."
